title: Salman Bin Kashif
author:
  name: Salman Bin Kashif
  email: sbinkas@clemson.edu
description: > # this means to ignore newlines until "show_excerpts:"
    This is Salman's personal webpage. The page features the details of his work, and the blogs he posts occasionally. 

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  # generate social links in footer
  social_links:
    twitter: salman_kashif21
    github:  sbkashif
    linkedin: salmanbinkashif

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - research.md
 - portfolio.md
 - resume.md
 - posts.md
 
# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  research:
    output: true
    permalink: /research/:path/

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio_item"
  - scope:
      path: ""
      type: "research"
    values:
      layout: "research_item"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Project display settings
project_thumbnail_height: 120px
portfolio_items_per_page: 3
blog_posts_per_page: 3

# Set excerpt separator for blog posts and portfolio items
excerpt_separator: <!--more-->

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

